/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/orchestrator/events/{eventType}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** @description Handle orchestrator events */
    post: operations['OrchestratorController_handleEvent']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/orchestrator/status': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** @description Get infrastructure status */
    get: operations['StatusController_getStatus']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    AWSEventBridgeBody: {
      account: string
      detail?:
        | {
            [key: string]: string | number | unknown
          }
        | string
        | number
        | unknown[]
        | unknown
      /** @enum {string} */
      'detail-type':
        | 'TENANT_PROVISIONING'
        | 'TENANT_DEPROVISIONING'
        | 'TENANT_PROVISIONING_SUCCESS'
        | 'TENANT_PROVISIONING_FAILURE'
        | 'TENANT_DEPLOYMENT'
        | 'TENANT_DEPLOYMENT_SUCCESS'
        | 'TENANT_DEPLOYMENT_FAILURE'
      id: string
      region: string
      resources: unknown[]
      source: string
      time: string
      version: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  OrchestratorController_handleEvent: {
    parameters: {
      query?: never
      header?: never
      path: {
        eventType: string
      }
      cookie?: never
    }
    requestBody?: {
      content: {
        'application/json': components['schemas']['AWSEventBridgeBody']
      }
    }
    responses: {
      /** @description Default Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Default Response */
      500: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  StatusController_getStatus: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Infrastructure status retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Failed to retrieve infrastructure status */
      500: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
}
